name: Leadify Monitoring Cron Jobs

on:
  schedule:
    # Lightweight scanning every 3 minutes
    - cron: '*/3 * * * *'
    # Heavy qualification every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scan-reddit:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/3 * * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Scan for new Reddit posts
        run: |
          echo "🔍 Starting Reddit scan..."
          curl -X GET "${{ secrets.DEPLOYMENT_URL || 'https://your-domain.vercel.app' }}/api/monitoring/scan" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail-with-body \
            --show-error

  qualify-leads:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/10 * * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Qualify potential leads
        run: |
          echo "🎯 Starting lead qualification..."
          # You'll need to set ORGANIZATION_IDS as a comma-separated list in GitHub secrets
          IFS=',' read -ra ORG_IDS <<< "${{ secrets.ORGANIZATION_IDS }}"
          for org_id in "${ORG_IDS[@]}"; do
            echo "Processing organization: $org_id"
            curl -X GET "${{ secrets.DEPLOYMENT_URL || 'https://your-domain.vercel.app' }}/api/monitoring/qualify?organizationId=$org_id" \
              -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
              -H "Content-Type: application/json" \
              --fail-with-body \
              --show-error
          done 